// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATYVkjxvIA_TyjGxcMHAjBD3gX7Tx0ZaA',
    appId: '1:938465502008:web:200d3b6360754dbb9d97cd',
    messagingSenderId: '938465502008',
    projectId: 'skillsync-523fa',
    authDomain: 'skillsync-523fa.firebaseapp.com',
    storageBucket: 'skillsync-523fa.firebasestorage.app',
    measurementId: 'G-EVZRXXBE80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp6u857qykCx0uDLZeox7pvtuIYWmH-sM',
    appId: '1:938465502008:android:250d7e08485ec0ae9d97cd',
    messagingSenderId: '938465502008',
    projectId: 'skillsync-523fa',
    storageBucket: 'skillsync-523fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBifT5owqtoIoa1U34jiYTmyUpZ76FLDeo',
    appId: '1:938465502008:ios:a267ca030755679f9d97cd',
    messagingSenderId: '938465502008',
    projectId: 'skillsync-523fa',
    storageBucket: 'skillsync-523fa.firebasestorage.app',
    iosBundleId: 'com.example.skillSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBifT5owqtoIoa1U34jiYTmyUpZ76FLDeo',
    appId: '1:938465502008:ios:a267ca030755679f9d97cd',
    messagingSenderId: '938465502008',
    projectId: 'skillsync-523fa',
    storageBucket: 'skillsync-523fa.firebasestorage.app',
    iosBundleId: 'com.example.skillSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATYVkjxvIA_TyjGxcMHAjBD3gX7Tx0ZaA',
    appId: '1:938465502008:web:fb43ce5bd9e962769d97cd',
    messagingSenderId: '938465502008',
    projectId: 'skillsync-523fa',
    authDomain: 'skillsync-523fa.firebaseapp.com',
    storageBucket: 'skillsync-523fa.firebasestorage.app',
    measurementId: 'G-HT5Y4M55C6',
  );
}
